### ISSUE TITLE
Can't install packages with string binary entry

### ISSUE THREAD

**Issue by goncharov** [Schniz/gpkg#23]
Some packages may define executable in package.json as string instead of object when there's single binary (https://docs.npmjs.com/cli/v7/configuring-npm/package-json#bin).
But seems gpkg expect `bin` to be an object so install of packages like `prettier` are failed:
https://github.com/Schniz/gpkg/blob/2ddc6379998fa1d5c64dc700bef3cc1ca20cf978/gpkg/src/install_package.rs#L15-L17

```
> gpkg install prettier

added 1 package, and audited 2 packages in 2s

found 0 vulnerabilities
[gpkg_cli/./src/commands/install.rs:36] err = SerdeError(
    Error("invalid type: string \"./bin-prettier.js\", expected a map", line: 5, column: 28),
)
thread 'main' panicked at 'not implemented', gpkg_cli/./src/commands/install.rs:37:17
```

**Comment by soerson** [comment]
Hi there! Any updates on the issue?

**Comment by Schniz** [comment]
Hi! sorry for the bug and not replying to the issue. I tried to investigate a bit (it's not a real issue to solve this in code, but I wanted to reproduce it first). I can't find any package that has a stringified binary path in the npm registry. It seems like it is being normalized by the registry itself. as of today, this is the response for https://registry.npmjs.org/prettier/latest:

```json
{
  "name": "prettier",
  "version": "2.3.2",
  "description": "Prettier is an opinionated code formatter",
  "bin": { "prettier": "bin-prettier.js" },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/prettier/prettier.git"
  },
  "homepage": "https://prettier.io",
  "author": { "name": "James Long" },
  "license": "MIT",
  "main": "./index.js",
  "browser": "./standalone.js",
  "unpkg": "./standalone.js",
  "engines": { "node": ">=10.13.0" },
  "scripts": {
    "prepublishOnly": "node -e \"assert.equal(require('.').version, require('..').version)\""
  },
  "bugs": { "url": "https://github.com/prettier/prettier/issues" },
  "_id": "prettier@2.3.2",
  "_nodeVersion": "14.15.4",
  "_npmVersion": "6.14.10",
  "dist": {
    "integrity": "sha512-lnJzDfJ66zkMy58OL5/NY5zp70S7Nz6KqcKkXYzn2tMVrNxvbqaBpg7H3qHaLxCJ5lNMsGuM8+ohS7cZrthdLQ==",
    "shasum": "ef280a05ec253712e486233db5c6f23441e7342d",
    "tarball": "https://registry.npmjs.org/prettier/-/prettier-2.3.2.tgz",
    "fileCount": 33,
    "unpackedSize": 20345894,
    "npm-signature": "-----BEGIN PGP SIGNATURE-----\r\nVersion: OpenPGP.js v3.0.13\r\nComment: https://openpgpjs.org\r\n\r\nwsFcBAEBCAAQBQJg1uU8CRA9TVsSAnZWagAAIjwP/2R5Gg0+ml5+EvhpaFfY\nI3xNZsfDCuqjjGyb8gtu8cbUf+SQJWDv/N5V6lzs/vsNy9dbA8Gu2Zr40sj+\nsQSj94txo+kISskrAtdVo69v2PTQGC/C3EM6q3wpP6beSkq9V0oBSc7DHiNq\njYL6Cqsd9XnNswQWJO86HnQqw06laBwLk6fEaL+kJz5RfUlAjMoEWs8bd4ue\nwQs/ApyL8NWkY9vU1JaLYvnsOdRmFRrFWAdrCCJpqGbSMn/HW4WeIX4t2o6f\nFeQba9X9tfP/lfeSDXA8PiOSdhgu+2612jz05c+1RnLBuami8SOjlr+uxchC\nZRHuYra0IXHz5nquy3lDmhkghTWtnh/a1j/xY5T//anV9Z4r7eZwNkugkP4r\nHYT0+ja8DbrJNtMDkeby8JgEPU0sqA9BWtP3gFPVnjo9XQcYpVKybvai9unP\nayfuIb/Z1hmJXf9fVwNI/NAcvzJIfJxWYrJPEy61cBIPWLt5wKp/jEl6Co99\nqcRIAXmLdSIw6a5CR4vX5ewPeOW4KHEQm6iD4sR3W6wcCof8Bx5NoTeUwvtf\nv51HXzODlpxBjdboj0NYDbnp4e6W53Obu+1YO90UCI2W6qsl8x/dphVcUEP+\nkuCEEw6GFUBWrpamCwVbxXSOwQjSSeOH8aIHfcwfQBPJ7uUGtglzq+Tghutk\nYIVv\r\n=65aO\r\n-----END PGP SIGNATURE-----\r\n"
  },
  "_npmUser": { "name": "sosukesuzuki", "email": "aosukeke@gmail.com" },
  "directories": {},
  "maintainers": [
    { "name": "jlongster", "email": "longster@gmail.com" },
    { "name": "lydell", "email": "simon.lydell@gmail.com" },
    { "name": "thorn0", "email": "georgii.dolzhykov@gmail.com" },
    { "name": "vjeux", "email": "vjeuxx@gmail.com" },
    { "name": "suchipi", "email": "me@suchipi.com" },
    { "name": "duailibe", "email": "lucasds@gmail.com" },
    { "name": "ikatyang", "email": "ikatyang@gmail.com" },
    { "name": "azz", "email": "lucas@azzola.dev" },
    { "name": "sosukesuzuki", "email": "aosukeke@gmail.com" }
  ],
  "_npmOperationalInternal": {
    "host": "s3://npm-registry-packages",
    "tmp": "tmp/prettier_2.3.2_1624696123751_0.5119283456807497"
  },
  "_hasShrinkwrap": false
}
```

As you can see we have that `"bin": { "prettier": "bin-prettier.js" }`, although prettier does define `"bin": "bin-prettier.js"` like you mentioned in the issue.

Do you try to install a local version of prettier? I wonder what's the difference

**Comment by goncharov** [comment]
Hi!
Yep, seems all packages on https://registry.npmjs.org/ are normalized but installed package.json is different https://unpkg.com/browse/prettier@2.3.2/package.json (another example of eslint_d in [registry](https://registry.npmjs.org/eslint_d/latest) and [unpkg](https://unpkg.com/browse/eslint_d@11.0.0/package.json))

> Do you try to install a local version of prettier?

No. I just do `gpkg install prettier` which installs package from the registry. 
Installed package.json contains `"bin": "./bin-prettier.js"`

For personal use I have made [this change](https://github.com/goncharov/gpkg/commit/605a9fda6adcb997a7f56e24963f27038a203aae) but it's looks not really pretty

**Comment by Schniz** [comment]
Ah, funny! Seems like npm@6 does normalize the `bin` values, while npm@7 does not. By the way, your change looks very clean and nice. Would be happy to merge it 😃  I've been trying to integrate [miette](https://docs.rs/miette) by @zkat and it produces a nice output that shows where the error is:

![image](https://user-images.githubusercontent.com/2054772/132574058-efffdc5a-87d5-4de6-9774-76b4cde72416.png)

Would you consider PRing your change so I'll be able to support this use case? 😃

**Comment by zkat** [comment]
Omg that looks so good

**Comment by goncharov** [comment]
I doesn't know about this change in npm@7 (seems was done there https://github.com/npm/rfcs/blob/latest/implemented/0013-no-package-json-_fields.md). 
miette's output look very nice. Love it!
